### ISSUE TITLE
Google authentication causes an error

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#1]
Trying to authenticate to https://learn.test.up2university.eu/login/index.php, clicking "Login via SAML2". I choose Google icon. I get "Choose an account" screen from Google. I select an email, and it ends up with an Unhandled exception. The same problem appears also when I'm not earlier authenticated to Google - then the error appears after choosing Google icon and authenticating to Google.

Additionally, the next click at "Login via SAML2" within this user session ends up with an error at the Moodle side: "SAML2 exception: Responder: SimpleSAML_Error_Exception: ldap:LdapConnection->search_manual : No search filters defined".

CC @athird

**Comment by foobarable** [comment]
So it looks like google changed the attributes they are sending out. We have to adjust our mappings accordingly.

**Comment by foobarable** [comment]
I think we found the issue

**Comment by foobarable** [comment]
Can you test again?

**Comment by michzimny** [comment]
It's still the same. 
Error tracking codes I got now: 208e009c29, 662c57881b

**Comment by foobarable** [comment]
@michzimny Check again and please create another issue for the moodle problem.

**Comment by michzimny** [comment]
Now it works!

The moodle part is now probably hard to being reproduced.
