### ISSUE TITLE
login form

### ISSUE THREAD

**Issue by vasilg** [up2university/single-sign-on#11]
[https://learn.test.up2university.eu/ ](url)
here, there is a login form asking for username and password (both required fields). Upon clicking "log in" the user is taken to a different page asking them to choose a login method.
As far as I can tell, the username and password entered in the first form are never taken into account. 

So, it is not clear what the user is supposed to enter there (or why); especially for new users that don't have an account yet.

Did I miss something?

**Comment by michzimny** [comment]
@vasilg, are you able to reproduce? It seems to be fixed.
