### ISSUE TITLE
links should be more visible and user experience should be improved

### ISSUE THREAD

**Issue by vasilg** [up2university/single-sign-on#12]
![up2u5](https://user-images.githubusercontent.com/36266155/36027708-05b2c1da-0da5-11e8-9221-8d8e2088845d.png)

it would also be nice to have a clear option to login to the platform and be directed there somehow...

**Comment by michzimny** [comment]
related: #5

**Comment by foobarable** [comment]
I placed a link to the password reset functionality more prominently. Do we need a link to to the other functions as well?

**Comment by michzimny** [comment]
@foobarable, would it be possible to redirect a user after registration to continue authentication to the service they came from? It is about user experience and ease of use.

Let me clarify:

1. I'm in Moodle and want to log in.
2. Opening SSO
3. Registration...
4. After the registration, I see the screen as above. How to go now to Moodle that I wanted to log in to?

Opening a new tab and manually entering Moodle address is not a good way.

As a minimal solution, we could just add "target=blank" to link "register here". Then after the registration, I can just close the current tab, and I'm back in the authentication step. What do you think?

**Comment by foobarable** [comment]
With the current implementation of the selfregister module this is not possible. Would need a rewrite of the GEANT module. So I think we need to stick with the workarround.

**Comment by michzimny** [comment]
If by "workaround" you mean my proposal with "target=blank", then I'm fine with it.

**Comment by foobarable** [comment]
Implemented the target=blank in the i18n module for german and english
