### ISSUE TITLE
"User ID" attribute

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#14]
During the local registration, a user is asked to provide "User ID", "E-mail", and other properties. Then, when logging in, the user is said to provide "Username". I've been confused when I provided my "User ID" to the "Username" field and the authentication process failed. 

It seems "Username"="E-mail". It is not user-familiar.

Could we change "Username" label to "E-mail" and also remove "User ID" from the registration form? Is that property necessary? Could it be generated automatically or set to be the same as e-mail, etc.

**Comment by foobarable** [comment]
Ofc, on it.

**Comment by michzimny** [comment]
I'm not the only one who gets caught in the trap - #34.

**Comment by michzimny** [comment]
Could we just change the labels of the fields?

**Comment by michzimny** [comment]
And hide "user ID" field during registration?

**Comment by m0ark** [comment]
This is resolved. Please check and confirm.

**Comment by michzimny** [comment]
I see it's solved in test.

When could we plan to deploy to production? I think any day this week is ok.

**Comment by m0ark** [comment]
You can chose:
Wednesday 15:00 UTC+2
Thursday 11:00 UTC+2
or delay to next week.

Maintainance should only take ~15 minutes including functional testing.

**Comment by michzimny** [comment]
Let's do it tomorrow at 11:00 UTC+2. 

Please confirm.

**Comment by m0ark** [comment]
Ok, the maintainance will happen tomorrow.

**Comment by m0ark** [comment]
Maintainance is finished now. Tested everything at least once.
Please confirm and close this issue.

**Comment by michzimny** [comment]
It works, thanks.
