### ISSUE TITLE
Register new instance CERNBox at SSO side

### ISSUE THREAD

**Issue by ebocchi** [up2university/single-sign-on#18]
Please register at the SSO side the test instance https://cernbox-gamma.test.up2university.eu/cernbox

Metadata* available here:
https://cernbox-gamma.test.up2university.eu/cernbox/Shibboleth.sso/Metadata

* The test instance is intended for functional tests and development only, and it uses autogenerated metadata.

**Comment by michzimny** [comment]
This instance has self-signed HTTPS certs. If it's a problem for anyone, please let me know.

**Comment by foobarable** [comment]
Added it to the config. Will deploy it soon.

**Comment by foobarable** [comment]
Deployed. Can you test?

**Comment by ebocchi** [comment]
I got a Welcome page reporting "Metadata not found"

```
Unable to locate metadata for 'https://cernbox-gamma.test.up2university.eu/cernbox/shibboleth'
This is most likely a configuration problem on either the service provider or identity provider.
[cut...]
```

**Comment by foobarable** [comment]
Feb 23 13:59:17 ssoUp2u simplesamlphp[29347]: 6 [6a0b9286d7] SAML2.0 - IdP.SSOService: Accessing SAML 2.0 IdP endpoint SSOService
Feb 23 13:59:17 ssoUp2u simplesamlphp[29347]: 3 [6a0b9286d7] SimpleSAML_Error_MetadataNotFound: METADATANOTFOUND('%' => '\'https://cernbox-gamma.test.up2university.eu/cernbox/shibboleth\'')

**Comment by foobarable** [comment]
Let me double check if I can fetch the metadata manually

**Comment by ebocchi** [comment]
I can fetch the metadata with
```
 wget https://cernbox-gamma.test.up2university.eu/cernbox/Shibboleth.sso/Metadata --no-check-certificate
```

**Comment by foobarable** [comment]
I think invalid (aka selfsigned) SSL-certificates are an issue. Could you use letsencrypt at least?

**Comment by ebocchi** [comment]
Could it be related to certificates?
At the moment we are running on self-signed ones.

**Comment by foobarable** [comment]
See comment before your comment ;)

**Comment by ebocchi** [comment]
Working on it

**Comment by ebocchi** [comment]
There are now proper (i.e., letsencrypt) certs on the server but no luck for the metadata retrieval

**Comment by foobarable** [comment]
I have to trigger a new try from sso side. Stay tuned.

**Comment by foobarable** [comment]
Okay, SSO could fetch the metadata now.

**Comment by ebocchi** [comment]
Yes! Cool!
Now it is on me again. Thanks a lot!
