### ISSUE TITLE
Register new instance SWAN at SSO side

### ISSUE THREAD

**Issue by ebocchi** [up2university/single-sign-on#19]
Please register at the SSO side the test instance https://swan-gamma.test.up2university.eu/

Metadata* available here:
https://swan-gamma.test.up2university.eu/Shibboleth.sso/Metadata

Let's Encrypt certificates are already in place ;)

*The test instance is intended for functional tests and development only, and it uses autogenerated metadata.

**Comment by foobarable** [comment]
Done

**Comment by ebocchi** [comment]
Unfortunately, I get the "Metadata not found" page as in the case of CERNBox.
Could you please try to deploy again?
I discovered an issue with the certs that has been fixed in the meantime.

Thanks!

**Comment by foobarable** [comment]
There is a metadata file which seems to be recent and non empty.
`-rw-r--r-- 1 www-data www-data  12K Feb 27 08:01 https%3A%2F%2Fswan-gamma.test.up2university.eu%2Fshibboleth.serialized`

Could you try again?

**Comment by ebocchi** [comment]
SWAN gamma test has been registered, thanks!
Currently developing a custom authenticator to allow user access.
