### ISSUE TITLE
Edugain Unhandled Exception on Up2U Production Instance

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/single-sign-on#22]
Hello,

I tried to sign in on Up2U production instance and an unhandled exception was thrown with tracking number 500be05023

![image](https://user-images.githubusercontent.com/13375110/37147577-15243f96-22d0-11e8-9540-40c8052c8db1.png)

**Comment by foobarable** [comment]
Having a look into it.

**Comment by foobarable** [comment]
Hi,

your IDP does not release either uid or eduPersonTargetedID

**Comment by Dimitrispant** [comment]
I talked with my IdP and they told me that I have to inform them about what attributes we want to release.

**Comment by foobarable** [comment]
'givenName','sn','mail, eduPersonTargetedID, 'eduPersonPrincipalName', if possible

**Comment by Dimitrispant** [comment]
Thank you! I already sent them as they were also in this link https://github.com/up2university/single-sign-on/blob/master/attributes.md
