### ISSUE TITLE
Metadata Configuration for selcont.up2university.eu

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/single-sign-on#23]
The metadata file can be found here

https://selcont.up2university.eu/Shibboleth.sso/Metadata

**Comment by foobarable** [comment]
Added in in our testing system, will deploy very soon

**Comment by foobarable** [comment]
Can you check if it works?

**Comment by Dimitrispant** [comment]
I checked it, but I have another issue. I try to sign in with my credentials and then it just loops. I checked vhost and it seems ok. What may be the problem?

**Comment by foobarable** [comment]
How can I reproduce? Go to selcont.up2university.eu and.. ?

Visiting https://selcont.up2university.eu/Shibboleth.sso/Login seemed to work for me, I get redirected once

**Comment by Dimitrispant** [comment]
You can go here https://selcont.up2university.eu/wp-login.php?redirect_to=https%3A%2F%2Fselcont.up2university.eu%2Fwp-admin%2F&reauth=1. Then you select the option "Log In with Shibboleth". After choosing your institution (EduGAIN) and entering your credentials it loops.

**Comment by foobarable** [comment]
Could reproduce. It works in the test system? Are there any differences in the apache config?

**Comment by foobarable** [comment]
And, can you show me the apache and shibboleth.xml configuration?

**Comment by Dimitrispant** [comment]
In test instance I have the same issue but it seems to be a vhost issue. For the production instance these are the files 
 vhost https://pastebin.com/9zW9EZr0
shibboleth.xml https://pastebin.com/tYEZ8Yf2

**Comment by Dimitrispant** [comment]
I just saw that lets-encrypt creates another file for vhost

https://pastebin.com/8K6JvhXE

**Comment by foobarable** [comment]
Okay, you don't have any protected resources that would cause another redirect. Could we have a small call to figure this out?

**Comment by Dimitrispant** [comment]
Of course. Can you give me your skype id?

**Comment by Dimitrispant** [comment]
The production instance is now fine. I will check also the test instance in order to work. Thanks a lot!
