### ISSUE TITLE
SSO does not support IPv6

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#26]
Just for the record.

**Comment by foobarable** [comment]
IP-V6 introduction for the network from sso is now an official todo

**Comment by 8c44klfls** [comment]
I guess we are talking about an IPv6 adress for the https://sso.up2university.eu/. I will take care.

**Comment by michzimny** [comment]
That's right, thanks.

**Comment by foobarable** [comment]
sso.up2university.eu is now available at 2001:638:60f:e013::18:18. Can GEANT update the DNS records?

**Comment by michzimny** [comment]
Done.

**Comment by 8c44klfls** [comment]
Thnx. philipp.



---
Dr. Philipp Wieder
Deputy Head Data Center
Group Leader eScience
GWDG - Gesellschaft für wissenschaftliche Datenverarbeitung mbH Göttingen
Am Faßberg 11, 37077 Göttingen, Germany
www.gwdg.de

M +49 151 42672933
T +49 551 201-1576
F +49 551 201-2150
E philipp.wieder@gwdg.de

Geschäftsführer: Prof. Dr. Ramin Yahyapour
Aufsichtsratsvorsitzender: Prof. Dr. Norbert Lossau
Sitz der Gesellschaft: Göttingen
Registergericht: Göttingen
Handelsregister-Nr. B 598

Zertifiziert nach ISO 9001

Von: Michał Zimniewicz <notifications@github.com>
Antworten an: up2university/single-sign-on <reply@reply.github.com>
Datum: Freitag, 10. August 2018 um 14:56
An: up2university/single-sign-on <single-sign-on@noreply.github.com>
Cc: Philipp Wieder <philipp.wieder@gwdg.de>, Comment <comment@noreply.github.com>
Betreff: Re: [up2university/single-sign-on] SSO does not support IPv6 (#26)


Done.

**Comment by foobarable** [comment]
So, for SSO this is solved.
