### ISSUE TITLE
Register CERNBox at SSO

### ISSUE THREAD

**Issue by ebocchi** [up2university/single-sign-on#27]
Base URL: https://cernbox.test.up2university.eu/cernbox
Metadata available at: https://cernbox.test.up2university.eu/cernbox/Shibboleth.sso/Metadata

The web server runs with certificates issued by Let's Encrypt Authority X3.

**Comment by foobarable** [comment]
Deployed, can you check?

**Comment by ebocchi** [comment]
I still get metadata not found:

![screenshot from 2018-03-14 17-01-30](https://user-images.githubusercontent.com/16349448/37414489-82963696-27a9-11e8-84bf-22c45153b557.png)

**Comment by foobarable** [comment]
Sorry, puppet agent was disabled. Switched it on and deployed again

**Comment by ebocchi** [comment]
And now again "metadata not found" but with the typical Up2U white theme

**Comment by foobarable** [comment]
Yeah, seems there are issues with the deployment. Fixing.

**Comment by ebocchi** [comment]
Up and running. Thanks!

**Comment by foobarable** [comment]
@ebocchi Try again please

**Comment by ebocchi** [comment]
It works no problem for me. Any changes?
