### ISSUE TITLE
Register SWAN at SSO

### ISSUE THREAD

**Issue by ebocchi** [up2university/single-sign-on#28]
Base URL: https://swan.test.up2university.eu/
Metadata available at: https://swan.test.up2university.eu/Shibboleth.sso/Metadata

The web server runs with certificates issued by Let's Encrypt Authority X3.

**Comment by foobarable** [comment]
The metadata are not accessible right now

**Comment by ebocchi** [comment]
Could you please retry now?
I see the metadata at the link mentioned above

**Comment by foobarable** [comment]
Not it works. Didn't the last time I checked. Will register now.

**Comment by foobarable** [comment]
Deployed, test please.

**Comment by ebocchi** [comment]
I get a "Down for maintenance" page

**Comment by foobarable** [comment]
Oh, right. Now

**Comment by ebocchi** [comment]
Yep! It works!
Thanks a lot
