### ISSUE TITLE
SSO learn.test.up2university from gmail doesn't work

### ISSUE THREAD

**Issue by Dimitrispant** [up2university/single-sign-on#29]
I tried to sign in from a gmail account and I get this error:

![image](https://user-images.githubusercontent.com/13375110/37595078-11270276-2b80-11e8-8608-f9fd7a9ec3d4.png)

**Comment by foobarable** [comment]
Works for me. Do you have your gmail-address already in a selfregistered account?

**Comment by michzimny** [comment]
> Do you have your gmail-address already in a selfregistered account?

If this is the problem (other user account with the same email address) then we should probably provide a human-readable explanation as our users might experience such issues too.

**Comment by foobarable** [comment]
Yes, we need an error message for that. It's already on our todo list.

**Comment by Dimitrispant** [comment]
@foobarable I had this issue on a normal gmail account that it wasn's used in a selfregistered account. Now its ok. But as @michzimny mentioned it would be nice to add an error message for this case, as two users tried to do that on the training

**Comment by michzimny** [comment]
#6
