### ISSUE TITLE
Missing attribute

### ISSUE THREAD

**Issue by vogias** [up2university/single-sign-on#3]
The mail attribute is missing from sso responses

**Comment by foobarable** [comment]
It looks like simplesamlphp has some issues encoding some of the attributes.

Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] SimpleSAML_Error_Exception: Error 2 - Invalid argument supplied for foreach()
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] Backtrace:
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 11 /var/simplesamlphp/www/_include.php:86 (SimpleSAML_error_handler)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 10 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php:758 (sspmod_saml_IdP_SAML2::encodeAttributes)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 9 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php:956 (sspmod_saml_IdP_SAML2::buildAssertion)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 8 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php:45 (sspmod_saml_IdP_SAML2::sendResponse)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 7 /var/simplesamlphp/lib/SimpleSAML/IdP.php:287 (SimpleSAML_IdP::postAuthProc)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 6 /var/simplesamlphp/lib/SimpleSAML/IdP.php:333 (SimpleSAML_IdP::postAuth)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 5 /var/simplesamlphp/lib/SimpleSAML/Auth/Source.php:229 (SimpleSAML_Auth_Source::loginCompleted)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 4 /var/simplesamlphp/lib/SimpleSAML/Auth/Source.php:145 (SimpleSAML_Auth_Source::completeAuth)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 3 /var/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:790 (sspmod_saml_Auth_Source_SP::onProcessingCompleted)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 2 /var/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:717 (sspmod_saml_Auth_Source_SP::handleResponse)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:257 (require)
Jan 26 15:30:16 ssoUp2u simplesamlphp[57358]: 3 [3627821e4e] 0 /var/simplesamlphp/www/module.php:135 (N/A)
Jan 26 15:30:16 ssoUp2u simpl

**Comment by foobarable** [comment]
@vogias Can you try again? I think we found the issue (at least I could get the eMail attribute now)

**Comment by vogias** [comment]
@foobarable It worked!

**Comment by foobarable** [comment]
Perfect, will close the issue then.
