### ISSUE TITLE
Authentication by Facebook

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#31]
I've read that Facebook authentication is currently off.

Shoudn't we disable Facebook button in the SSO for as long as it is not available? Now a user clicks the button and gets to an error message.

CC @iliashatzakis

**Comment by foobarable** [comment]
Check the test system via learn-dev.test.up2university.eu. Did it 
already there, but I hesitate to deploy to production during the training.

**Comment by michzimny** [comment]
Ok, fine.

**Comment by iliashatzakis** [comment]
No, please go ahead and remove it… 
It’s misleading, we have to tell them to not go with FB…

BTW, we are using the pedagogy instance for the training, not production 


https://learn.test.up2university.eu/

**Comment by foobarable** [comment]
Facebook auth is back again in the testing system. Feel free to test.

**Comment by michzimny** [comment]
It works for me.

**Comment by foobarable** [comment]
When shall we deploy to production?

**Comment by iliashatzakis** [comment]
doesn't here :(

**Comment by foobarable** [comment]
@iliashatzakis any more details?

**Comment by iliashatzakis** [comment]
dead, black... contrarily to google and twitter... we are talking about the test instance of moodle, right?

**Comment by foobarable** [comment]
Nope, the sso-testing instance is configured at learn-dev.test.up2university.eu

**Comment by iliashatzakis** [comment]
![image](https://user-images.githubusercontent.com/16252936/41025013-78b8e5e4-6979-11e8-82f0-ca87da5c56f8.png)

**Comment by iliashatzakis** [comment]
this one gives the interface (?)...

**Comment by iliashatzakis** [comment]
old interface..

**Comment by foobarable** [comment]
Klick on Login via SAML2 ;)

**Comment by iliashatzakis** [comment]
yeap! working just fine... I think we should pass it to the other 2 instances too, any cons for that?

**Comment by foobarable** [comment]
Fine with me. Update would take 1 puppet run  (~2 min). Do you want to announce it?

**Comment by iliashatzakis** [comment]
great, go ahead!

**Comment by michzimny** [comment]
@foobarable, we have a large real-time demonstration planned for tomorrow. Are there any other changes to be deployed that have not been tested and might cause any problems for us? If so, then please wait till Friday with the deployment.

**Comment by foobarable** [comment]
@michzimny I think we are fine to do it today. @m0ark Any doubts?

**Comment by m0ark** [comment]
It doesn't affect anthing else. The whole update process shouldn't even be noticable at all.

**Comment by michzimny** [comment]
Ok, let's do it.

**Comment by michzimny** [comment]
Now in production, during Facebook-based authentication, I get the following error from Facebook, and then another one from Moodle:

> Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

> SAML2 exception: Responder: SimpleSAML_Error_Error: BAD REQUEST

**Comment by m0ark** [comment]
Minor configuration issue. It works now.

**Comment by michzimny** [comment]
Ok, thanks.
