### ISSUE TITLE
Non-latin characters cause encoded metadata values

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#32]
This is because the internal LDAP stores names with special characters encoded and it is not decoded properly.

The details can be found in https://github.com/up2university/kuboxed/issues/6

**Comment by foobarable** [comment]
We had some issues reproducing the problem. Trying to get the LDAP data manually from PHP does not cause this issue.

**Comment by foobarable** [comment]
@michzimny Which of your accounts causes the problem?

**Comment by michzimny** [comment]
@foobarable, it happens in CERNBox when I authenticate with either Google or EduGAIN. It seems it is caused because of character 'ł' in my first name.

The details can be found in https://github.com/up2university/kuboxed/issues/6

**Comment by m0ark** [comment]
@michzimny There seems to be an issue with CERNBox. None of our other service providers shows this behaviour and the SAML attributes are transferred correctly.

**Comment by michzimny** [comment]
In https://github.com/up2university/kuboxed/issues/6, on 20th March, @ebocchi reported that this is what CERNBox receives from the SSO:
displayName is empty
givenName is ": TWljaGHFgg=="
surname is "Zimniewicz"

@ebocchi, could you please comment on this? We need to diagnose on which side we have a problem here.

**Comment by ebocchi** [comment]
@michzimny The issue has been fixed. Please, verify it.
New users will be stored in the LDAP correctly now that SSO forwards special characters with unicode encoding. 
Old usernames have been manually fixed.

**Comment by michzimny** [comment]
I cannot test it for the moment because of https://github.com/up2university/single-sign-on/issues/38

**Comment by michzimny** [comment]
Closing the issue here as it seems to be on the CERNBox side :)

**Comment by ebocchi** [comment]
Fixed on the CERNBox side ;)
