### ISSUE TITLE
Up2U Login account registration -- cannot authenticate

### ISSUE THREAD

**Issue by moscicki** [up2university/single-sign-on#34]
Hi,

I registered a new account following "Up2U Login" option at the SSO (I gave my gmail address):

![image](https://user-images.githubusercontent.com/621965/39521182-bc621a90-4e0d-11e8-850c-c16c89d7079b.png)

I got the email and I set the password correctly but I cannot login:

![image](https://user-images.githubusercontent.com/621965/39521090-5db68bf2-4e0d-11e8-8f7a-371d11f1fd85.png)

**Comment by michzimny** [comment]
Kuba, could your issue be related to #14? The username field expects your e-mail address, not "user ID"...

**Comment by moscicki** [comment]
If I login with my email address + password then everything works OK. Seems the same issue as yours (?).

**Comment by michzimny** [comment]
Ok, so I'm closing this one as it seems to be a duplicate.
