### ISSUE TITLE
Self registered accounts are still created with old user ID

### ISSUE THREAD

**Issue by foobarable** [up2university/single-sign-on#37]

**Comment by foobarable** [comment]
Bug was fixed but we still have some self registered accounts with wrong IDs now.

**Comment by michzimny** [comment]
@foobarable, by 'old user IDs' you mean the old format?

**Comment by foobarable** [comment]
Yes, after looking again in the code of the selfregister module I found that  we still used the old generator for user ids. We threw it out and use the new ID in our code but until it's deployed we should disable the registration for now

**Comment by michzimny** [comment]
Could we plan a deployment ASAP instead of disabling the registration?

What about the user accounts with old ids? Might they be left as they are?

**Comment by foobarable** [comment]
No, we should delete or migrate them

**Comment by michzimny** [comment]
Can you give us the number of such users with old IDs?

What about the deployment?

**Comment by foobarable** [comment]
19 users with some being testusers, so not so critical. Lets try to schedule asap. Next week?

**Comment by foobarable** [comment]
@michzimny We deployed the fix, what should we do with the users with wrong ids?

**Comment by michzimny** [comment]
@foobarable, thanks. Could we leave those users as they are for some time, and then migrate them later? For how long could they stay untouched now?

**Comment by foobarable** [comment]
@michzimny I think those users may have problems when they try to log in into cern box because they do some mapping with the user ids

**Comment by michzimny** [comment]
@ebocchi, could be any problem in CERNBox that some users have still SSO IDs with the old schema, and others have the IDs with the new schema?

**Comment by michzimny** [comment]
@ebocchi, is the 'near future' simply the time when we put in place the eos-swan fix, related to ID mapping, that we have been discussing?

**Comment by ebocchi** [comment]
@michzimny, correct! The fix is now there and will be shipped with the upcoming software release. Then, it is just a matter of rebuilding the docker images.

**Comment by ebocchi** [comment]
Not sure we want to apply this to the "test" instance, though. Users will lose access to the data unless we migrate them (both user IDs and file ownership). Instead, we will be able to start the production instance with a clean mapping of user IDs.

**Comment by michzimny** [comment]
Guys, thank you for the updates. I think that we should keep the user accounts till the end of June, when the most of school activities will be suspended. I also think that we should not apply the fix to the test CERNBox. It's better now for the users to keep their accounts and possibly have no access to production CERNBox, when it gets deployed, than remove them completely.

**Comment by foobarable** [comment]
It's end of June now. What do we do with those accounts?

**Comment by michzimny** [comment]
It's not end of June yet. I will be in a couple of weeks :)

**Comment by michzimny** [comment]
@foobarable, it seems that the 19 accounts you once sent me can be deleted. Could you please just preserve a list of actually deleted accounts (i.e. user IDs, names) to be able to match a person with their user ID, just in case of any problems.

**Comment by m0ark** [comment]
I issued a complete dump. As soon as it's finished I will delete these accounts.

**Comment by m0ark** [comment]
The accounts are backed up and removed now.

**Comment by michzimny** [comment]
Thanks for the information. Is this issue considered closed now?

**Comment by m0ark** [comment]
Yes, it should be closed.
