### ISSUE TITLE
Add affiliation attribute

### ISSUE THREAD

**Issue by vogias** [up2university/single-sign-on#4]
Is it possible to add affiliation attribute?DSpace needs this for user group management when using shibboleth

**Comment by michzimny** [comment]
I think that user group information will be kept in Moodle, and other services will need to query Moodle for that information. We cannot use EduGAIN affiliation as the most of schools are not in EduGAIN, and so they will register their accounts locally at GWDG SSO.

Moreover, there is personal data protection issue and we don't want to process users' affiliation information.

**Comment by foobarable** [comment]
Hi, 

we currently don't have this information. If we have a central group solution in place and we can read the  information from our ldap it is possible to pass this attribute via SAML.

**Comment by michzimny** [comment]
Yes, it could be quite good solution to have SSO reading the group information from Moodle (or another group management service in the future) and pass it with other SAML attributes.

The group information in Moodle is not yet in place but in his today's email, Ilias gave a deadline for it for 15th February.

**Comment by m0ark** [comment]
How's the progress on this? It's there a source for group information that can be queried yet?

**Comment by michzimny** [comment]
There is no such information to be queried now. I'm closing the issue as this is rather a general architecture issue to be discussed in the future.
