### ISSUE TITLE
Link "register here" in test leads to production

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#41]
At https://sso.test.up2university.eu/simplesaml/module.php/multiauth/selectsource.php?AuthState=...
```
You can <a class="registerlink" href="https://sso.up2university.eu/simplesaml/module.php/selfregister/newUser.php">register here</a> for a new account.
```

**Comment by michzimny** [comment]
And now, I see "Array" instead of the registration link:
![capture](https://user-images.githubusercontent.com/1483196/41918570-ef24115c-795c-11e8-9c09-4194ecff6d82.PNG)

**Comment by foobarable** [comment]
I cannot reproduce this. Did you do somethine specific?

**Comment by michzimny** [comment]
Note that the issue is about the test instance of SSO.

I'm trying to authenticated to learn-dev Moodle.

**Comment by foobarable** [comment]
Ah, maybe @m0ark changed the translation backend. I will check it and adjust the theme accordingly

**Comment by m0ark** [comment]
It's fixed without changing translation backend though.
