### ISSUE TITLE
Register CommonSpaces at Up2U SSO

### ISSUE THREAD

**Issue by gtoffoli** [up2university/single-sign-on#45]
Base URL: https://test.commonspaces.eu/
Metadata available at: https://test.commonspaces.eu/saml2/metadata/

I sent a mail to Ralph Krimmel on July 4, on "Up2U - Info and contacts for Up2U-CommonSpaces integration", but got no answer yet.
I was asking some support, since CommonSpaces doesn't use PHP and I'm not expert of SAML2.
Thanks.

**Comment by gtoffoli** [comment]
@foobarable No problem, thank you.
I have to start testing the SP from the beginning, since I didn't test it with any other IDP.
I dont't know which version of the IDP is better to use. Please, tell me.
If I must use its testing version, I will change the SP configuration data from which the SP metadata are generated.

**Comment by gtoffoli** [comment]
Hi, I didn't get news about my request, nor I solicited them.
Now the SP described by https://test.commonspaces.eu/saml2/metadata/ is configured to be tested with the testing instance of the Up2U IdP.
Are those metadata ok for the Up2U SSO? Thanks!

**Comment by foobarable** [comment]
Yes, we can test those. They are already deployed.

**Comment by foobarable** [comment]
@gtoffoli Were you able to test the your instance?

**Comment by gtoffoli** [comment]
@foobarable No, thanks. I've just made a try.
1. got the screen to choose among several forms of login; chose "Login with UP2UID"
2. got the form "Welcome - Insert username ad password"; inserted the email toffoli@uni.net and the password
3. got "Not managed exception" screen; sent tracking id with some note.
By the way: in July I registered at the Up2U IdP in production with the email toffoli@uni.net; now I realized that my account is present also in the testing version: do you copy regularly the database from production to testing?

**Comment by gtoffoli** [comment]
@foobarable As I wrote in my previous comment, the first and only test that I made was unsuccessful. I don't know if, from the tracking id associated to the "Not managed exception" UI message issued by the IdP to the user, you are able to guess what could have happened. Can I do something to help debugging?

**Comment by foobarable** [comment]
@gtoffoli can you send a screenshot of the error page to rkrimme1@gwdg.de?

**Comment by foobarable** [comment]
@gtoffoli I could reproduce the issue with our test system. Could you point your common spaces instance to use our production sso for another test?

**Comment by foobarable** [comment]
Fixed in production
