### ISSUE TITLE
New users cannot authenticate in production

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#46]
If you authenticate for the first time, you currently get "Account could not be created!". Sample error id: 08f36ebe51

I've tested with Google accounts. Other users told me it's also an issue for EduGAIN. Maybe it's for all sources.

If you authenticate as an already existing Up2U user, then it's fine.

Older similiar issue: #42 

In addition, would you be able to monitor such effect somehow?

**Comment by foobarable** [comment]
@michzimny should be solved. The glassfish server of the idm had some issues with the heap memory.

**Comment by michzimny** [comment]
Thanks. 

@foobarable, would you be able to monitor it anyhow in the future?

**Comment by foobarable** [comment]
I can ask the administrators of the IDM system how they monitor it and how we can prevent stuff like that.
