### ISSUE TITLE
Problem with Edugain access

### ISSUE THREAD

**Issue by ivanoterouvigo** [up2university/single-sign-on#47]
Hi everyone!

From long time ago, I have the same problem trying to use Edugain access in both platforms.

https://learn.test.up2university.eu

and

https://learn.up2university.eu

I attached here some images of the error.

![moodle_learn_test_up2university_001](https://user-images.githubusercontent.com/11814769/48680379-38c9af00-eb9b-11e8-9e30-dc08d874a816.png)
![moodle_learn_test_up2university_002](https://user-images.githubusercontent.com/11814769/48680380-38c9af00-eb9b-11e8-8f84-b10172072fb1.png)
![moodle_learn_test_up2university_003](https://user-images.githubusercontent.com/11814769/48680381-38c9af00-eb9b-11e8-95b2-4375de3d498c.png)

Could you help me with this?

**Comment by foobarable** [comment]
@ivanoterouvigo Your IDP is missing the metadata from our IDP. Your IDP administrator need to fix this

**Comment by michzimny** [comment]
@foobarable, as it seems to be an issue for several edugain IDPs, could you please add a wiki page somehwere (maybe in this repository) explaining what should be fixed on the IDP side? Then all people could reference this description when talking to their IDP managers.

**Comment by foobarable** [comment]
@michzimny https://wiki.geant.org/display/eduGAIN/How+to+set+up+an+Identity+Provider+for+eduGAIN Its basically this

**Comment by ivanoterouvigo** [comment]
Thanks @foobarable, I agree with @michzimny. I also suggest to share in this wiki simple instance of diagram with a simple explanation of workflow.
For example. I don't know who is the IDP administrator of Spain.

**Comment by foobarable** [comment]
Okay, I will search better dokumentation. The geant wiki has alot of dead links

**Comment by foobarable** [comment]
@ivanoterouvigo https://wiki.geant.org/display/eduGAIN/Metadata+Flow+in+eduGAIN
