### ISSUE TITLE
Cannot authenticate via EduGAIN

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#51]
User ends up with a blank page (at url: https://sso.up2university.eu/simplesaml/module.php/saml/sp/saml2-acs.php/sso) when trying to authenticate to the production SSO with EduGAIN. It has been checked by people from several countries/institutions, either new users or already existing accounts.

It works fine for the test SSO.

@foobarable is included in a mail thread regarding this issue.

**Comment by foobarable** [comment]
Is this for one user or a general problem?

**Comment by michzimny** [comment]
It seems to be general. Two users are complaining in the email thread, and EduGAIN neither works for me.

**Comment by foobarable** [comment]
It should work right now.
