### ISSUE TITLE
Register production instance of CommonSpaces at Up2U SSO

### ISSUE THREAD

**Issue by gtoffoli** [up2university/single-sign-on#53]
Base URL: https://cs.up2university.eu/
Metadata available at: https://cs.up2university.eu/saml2/metadata/

Hi, I made the production deployment of the CommonS Platform (alias CommonSpaces).
As well as the test version, now it is hosted by the PSNC infrastructure.
Could you register it at the production instance of the Up2U SSO IdP?
Thanks!

**Comment by foobarable** [comment]
Well be included on the next deploy.

**Comment by gtoffoli** [comment]
Could I know when is the next deploy scheduled? Thanks.

**Comment by foobarable** [comment]
I can trigger it tomorrow morning at 9am CEST. There should be now downtime for the service.

**Comment by foobarable** [comment]
@gtoffoli Done
