### ISSUE TITLE
Web analytics

### ISSUE THREAD

**Issue by michzimny** [up2university/single-sign-on#54]
Please add Matomo tracking code to all pages as documented here:
https://wiki.geant.org/display/UP2U/Web+Analytics

**Comment by foobarable** [comment]
Will just use it for production instance. It will be included on the next deploy.

**Comment by michzimny** [comment]
@foobarable, when could you plan the next deploy? Is it feasible to do it within two weeks from now?

**Comment by michzimny** [comment]
Will it cause any longer downtimes? If not, we can do it now.

Any other changes to be included in the deployment? If so, then please book some time after the deployment in case anything goes wrong.

**Comment by foobarable** [comment]
No, no longer downtime. It's deployed. Can you check if it works?

**Comment by michzimny** [comment]
It's fine. Thanks.
