### ISSUE TITLE
Include privacy notice

### ISSUE THREAD

**Issue by foobarable** [up2university/single-sign-on#55]
[Up2U Project - Privacy Notice_22.02.2019.docx](https://github.com/up2university/single-sign-on/files/2904530/Up2U.Project.-.Privacy.Notice_22.02.2019.docx)

**Comment by foobarable** [comment]
Document will be hosted centrally. Just link needed.

**Comment by michzimny** [comment]
https://up2university.eu/wp-content/uploads/2019/02/privacy-notice.pdf

**Comment by michzimny** [comment]
https://cdn.test.up2university.eu/docs/privacy-notice.pdf

**Comment by foobarable** [comment]
@michzimny  The test domain is correct?

**Comment by michzimny** [comment]
Yes.

**Comment by michzimny** [comment]
@foobarable, I don't know if you know that, but there are also privacy notices in national languages being prepared: https://wiki.geant.org/display/UP2U/Privacy+notice
So, we need to look for a place to put them all in the SSO page.

**Comment by foobarable** [comment]
@michzimny If we use a good naming scheme we can link the anchor to the correct notice in the language that is currently chosen in the ui.

**Comment by michzimny** [comment]
I think it would be fine.

**Comment by michzimny** [comment]
Ok, could you please do so with the language-specific privacy notices? I think it's urgent.

**Comment by michzimny** [comment]
ping @foobarable

**Comment by m0ark** [comment]
@michzimny I will implement your requested change. The final URL will be https://cdn.test.up2university.eu/docs/privacy-notice-[language-abbreviation].pdf 
e.g.
https://cdn.test.up2university.eu/docs/privacy-notice-en.pdf 

Since we cannot know whether this file exists or not, you have to make sure that there is one for each language selectable.

Currently we support:
```
      'no' => 'Bokmål', // Norwegian Bokmål
      'nn' => 'Nynorsk', // Norwegian Nynorsk
      'se' => 'Sámegiella', // Northern Sami
      'sam' => 'Åarjelh-saemien giele', // Southern Sami
      'da' => 'Dansk', // Danish
      'en' => 'English',
      'de' => 'Deutsch', // German
      'sv' => 'Svenska', // Swedish
      'fi' => 'Suomeksi', // Finnish
      'es' => 'Español', // Spanish
      'fr' => 'Français', // French
      'it' => 'Italiano', // Italian
      'nl' => 'Nederlands', // Dutch
      'lb' => 'Lëtzebuergesch', // Luxembourgish
      'cs' => 'Čeština', // Czech
      'sl' => 'Slovenščina', // Slovensk
      'lt' => 'Lietuvių kalba', // Lithuanian
      'hr' => 'Hrvatski', // Croatian
      'hu' => 'Magyar', // Hungarian
      'pl' => 'Język polski', // Polish
      'pt' => 'Português', // Portuguese
      'pt-br' => 'Português brasileiro', // Portuguese
      'ru' => 'русский язык', // Russian
      'et' => 'eesti keel', // Estonian
      'tr' => 'Türkçe', // Turkish
      'el' => 'ελληνικά', // Greek
      'ja' => '日本語', // Japanese
      'zh' => '简体中文', // Chinese (simplified)
      'zh-tw' => '繁體中文', // Chinese (traditional)
      'ar' => 'ﺎﻠﻋﺮﺒﻳﺓ', // Arabic
      'fa' => 'پﺍﺮﺳی', // Persian
      'ur' => 'ﺍﺭﺩﻭ', // Urdu
      'he' => 'עִבְרִית', // Hebrew
      'id' => 'Bahasa Indonesia', // Indonesian
      'sr' => 'Srpski', // Serbian
      'lv' => 'Latviešu', // Latvian
      'ro' => 'Românește', // Romanian
      'eu' => 'Euskara', // Basque
```

**Comment by michzimny** [comment]
Ok, I will put a redirection to english for non-existing languages.

**Comment by m0ark** [comment]
It's already implemented in the staging environment. Please have a look at it if this is what you are looking for.
After confirmation I will also deploy this into production.

**Comment by michzimny** [comment]
Please set `target="_blank"` for this link.

**Comment by m0ark** [comment]
Done.

**Comment by michzimny** [comment]
Ok, so I think it works now as needed. Please deploy into production.

**Comment by m0ark** [comment]
It's deployed in production, too.

**Comment by michzimny** [comment]
Thanks.
