### ISSUE TITLE
Does the Up2U SSO IdP assign a unique ID to users, irrespective of the authentication option?

### ISSUE THREAD

**Issue by gtoffoli** [up2university/single-sign-on#57]
Does the Up2U SSO IdP assign a unique ID to users accessing the NGDLE tools, irrespective of the authentication option chosen?
More verbosely: it isn't clear to me what is the role of the Up2U SSO IdP, when in the screen with the header "Welcome Select an authentication source", the user selects "Federated Login" (Login with EduGain) or "Social Network Login". Does, even in these cases, the Up2U IdP create an entry in its database (if not already present) and assign to the user a unique ID, one that all NGDLE tools can retrieve when the user authenticates? That is, an ID that is GLOBAL within the Up2U NGDLE?
I've asked the same question to Ralph a couple of weeks ago, but got no answer yet.
I'm repeating the question since, inside the WP5 WG on Learning Analytics, we are trying to figure out the best shared way to identify the actor component in the xAPI statements sent by different platforms/tools; it has been suggested that a common user id would be preferable to the use of the email address. Thanks for any advice!

**Comment by foobarable** [comment]
Yes. we habe a unique id which is the SAML field uid.  What we currently cannot do is merge accounts if one registers with e.g. with a gmail address in the selfregister function and then tries to login via google login. This will fail. For anything else we have a field which is unique for all users.

**Comment by m0ark** [comment]
Up2U SSO is used as a community gateway which establishes homogeneous accounts for all users.
Every user is assigned a unique ID which (in addition to all other attributes) will be promoted to all eligible services (NGDLE tools) on user access.

**Comment by gtoffoli** [comment]
@foobarable @m0ark Many thanks for your comprehensive answers!
