### ISSUE TITLE
error: login via eduGAIN

### ISSUE THREAD

**Issue by vasilg** [up2university/single-sign-on#8]
When tried to login with eduGAIN at the test instance and after I have selected my institution and provided my surname and name, I got the following error.
![error](https://user-images.githubusercontent.com/36266155/35974004-252611fe-0ce0-11e8-848e-b5c30d652720.png)

**Comment by foobarable** [comment]
Hi @vasilg. Should not be an issue anymore. It broke when I configured the firewall to allow cern access.
