### ISSUE TITLE
Login via Social Network Login

### ISSUE THREAD

**Issue by vasilg** [up2university/single-sign-on#9]
I have tried to test logging in to our platform via Social Network Login (Facebook, Twitter and Google). I have successfully logged and then logged out (using all the above). One undesirable effect is that even after logging out of our platform, the user remains logged in on the auth provider (Facebook, Twitter, etc), even if there is no open tab.

I understand this is probably not our "problem", but has to do with the auth provider, but we could at least provide clear instructions that if you select this method of authentication, logging out from the up2u platform is not enough; you need to log out of the auth provider as well.

**Comment by michzimny** [comment]
Hi @vasilg, I agree. We're going to provide a set of instruction for end-users. I think it could be one of them.

I put it to the list of such information for end-users. See my last e-mails sent to WP5/7 mailing lists.
